apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels: {}
  name: jupyterhub-img
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/harryv98/jupyterhub-img
    from:
      kind: DockerImage
      name: quay.io/harryv98/jupyterhub-img:test
    name: latest
    referencePolicy:
      type: Source
