varReference:
- path: roleRef/namespace
  kind: RoleBinding
  apiGroup: authorization.openshift.io
- path: data
  kind: ConfigMap
- path: metadata/annotations/volume.beta.kubernetes.io\/storage-class
  kind: PersistentVolumeClaim
- path: subjects/namespace
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
- path: metadata/name
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
